# A list of containers that should run the pods of this component
containers: []
rollingUpdate:
  enabled: true

initContainers: []


service:
  type: ClusterIP
  labels: {}
  annotations: {}
  ports: []
  externalIPs: []

labels: {}
annotations: {}

ingress:
  disabled: false
  labels: {}
  annotations: {}
  certmanager: true
  rules: []

# Define persistent volumes here
# Then mount them in containers above
volumes: []

# Defines image pull secrets
# DevSpace CLI will append all pull secrets which are automatically created
# More infos on: https://devspace.cloud/docs/cli/image-building/workflow-basics#8-create-image-pull-secret
pullSecrets: []

serviceaccount: {}

configmap: {}
secrets: {}

externalSecrets: []
  # - name: my-external-secret
  #   annotations: {}
  #   refreshInterval: "0s"  # Set to "0s" to disable auto-refresh, or "1h", "5m", etc.
  #   secretStoreRef:
  #     name: my-secret-store
  #     kind: SecretStore
  #   target:
  #     name: my-external-secret
  #     creationPolicy: Owner
  #   data:
  #     - secretKey: MY_SECRET_KEY
  #       remoteRef:
  #         key: /path/to/parameter

extraObjects: []