{{- if .Values.externalSecrets }}
{{- range $externalSecrets := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecrets.name | quote }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
  {{- if $externalSecrets.annotations }}
  annotations:
    {{- range $annotationName, $annotationValue := $externalSecrets.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: {{ $externalSecrets.refreshInterval | default "0" | quote }}
  secretStoreRef:
    name: {{ $externalSecrets.secretStoreRef.name | quote }}
    kind: {{ $externalSecrets.secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ $externalSecrets.target.name | default $externalSecrets.name | quote }}
    creationPolicy: {{ $externalSecrets.target.creationPolicy | default "Owner" }}
    {{- if $externalSecrets.target.template }}
    template:
      {{- toYaml $externalSecrets.target.template | nindent 6 }}
    {{- end }}
  {{- if $externalSecrets.data }}
  data:
    {{- range $item := $externalSecrets.data }}
    - secretKey: {{ $item.secretKey | quote }}
      remoteRef:
        key: {{ $item.remoteRef.key | quote }}
        conversionStrategy: {{ $item.remoteRef.conversionStrategy | default "Default" | quote }}
        decodingStrategy: {{ $item.remoteRef.decodingStrategy | default "None" | quote }}
        metadataPolicy: {{ $item.remoteRef.metadataPolicy | default "None" | quote }}
        {{- if $item.remoteRef.property }}
        property: {{ $item.remoteRef.property | quote }}
        {{- end }}
        {{- if $item.remoteRef.version }}
        version: {{ $item.remoteRef.version | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if $externalSecrets.dataFrom }}
  dataFrom:
    {{- toYaml $externalSecrets.dataFrom | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}