{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default .Release.Name | quote }}
  labels:
    "app.kubernetes.io/name": {{ .Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ .Release.Service | quote }}
  {{- if .Values.secrets.annotations }}
  annotations:
    {{- range $annotationName, $annotationValue := .Values.secrets.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
  {{- end }}

type: Opaque
{{- if .Values.secrets.stringData }}
stringData:
{{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- if .Values.secrets.data }}
data:
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
