{{- if .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    "app.kubernetes.io/name": {{ .Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ .Release.Service | quote }}
    {{- range $labelName, $labelValue := .Values.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- range $annotationName, $annotationValue := .Values.serviceAccount.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
{{- end }}