apiVersion: v1
entries:
  component-chart:
  - apiVersion: v2
    created: "2025-12-16T12:36:45.076737283+05:30"
    description: A general purpose helm chart for deploying components of an application
    digest: 8e70363a2c4fcf8c90a73b244e78297ce19d581e93a77e523d438bdb9ddd542d
    name: component-chart
    urls:
    - https://rishang.github.io/common-chart/charts/component-chart-0.0.1.tgz
    version: 0.0.1
  loki-stack:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-12-16T12:36:45.114715691+05:30"
    dependencies:
    - condition: loki.enabled
      name: loki
      repository: https://grafana.github.io/helm-charts
      version: 6.42.0
    - condition: promtail.enabled
      name: promtail
      repository: https://grafana.github.io/helm-charts
      version: 6.17.0
    - condition: fluent-bit.enabled
      name: fluent-bit
      repository: https://grafana.github.io/helm-charts
      version: 2.6.0
    - condition: kube-prometheus-stack.enabled
      name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: 77.12.1
    description: A Helm chart for Loki logging stack with Grafana, Prometheus, Promtail,
      and Fluent Bit
    digest: f0df2e55781f4f24b4567f9a8b3b37fd02a08a00219d2ff218b5e6a5d7189402
    maintainers:
    - email: maintainer@example.com
      name: loki-stack-maintainer
    name: loki-stack
    type: application
    urls:
    - https://rishang.github.io/common-chart/charts/loki-stack-0.0.1.tgz
    version: 0.0.1
generated: "2025-12-16T12:36:45.076273726+05:30"
